from waflib.extras.layout import Solution

def options(optCtx):
    return

def configure(confCtx):
    solution = Solution.fromContext(confCtx)
    confCtx.env.solution = solution
    confCtx.env.append_value('CXXFLAGS', ['-Wall', '-Wextra', '-O2', '-g', '-std=c++0x', 
	    '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', 
	    '-fno-builtin-free', '-pthread'])
    confCtx.env.append_value('LDFLAGS', ["-rpath=\$ORIGIN/../lib:%s:%s" % (
	    solution.build_tree.lib, solution.install_tree.lib), '-z origin'])

def build(buildCtx):
    return

def install(installCtx):
    return
