from waflib.extras.layout import Solution

def options(optCtx):
    return

def configure(confCtx):
    solution = Solution.fromContext(confCtx)
    confCtx.env.solution = solution
    confCtx.env.append_value('CXXFLAGS', ['-Wall', '-Wextra', '-O2', '-g',
	    '-fno-builtin-malloc', '-fno-builtin-calloc', '-fno-builtin-realloc', 
	    '-fno-builtin-free', '-pthread', '-Wl,-z,origin'])

def build(buildCtx):
    return

def install(installCtx):
    return
