import os
from os.path import join

def build(buildCtx):
    buildCtx.program(
	    source=['config.cxx', 'main.cxx'], 
	    target='query_service',
	    use='BOOST',
	    includes=buildCtx.env.component.include_path_list,
	    libpath=buildCtx.env.component.lib_path_list,
	    cxxflags=['-Wl,-z,origin'],
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.bin)

def install(buildCtx):
    return
