from os.path import join

def build(buildCtx):
    for header in [
	    'process_utility.hpp',
	    'compiler_extensions.hpp']:
	buildCtx(
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header))

def install(buildCtx):
    return
