from os.path import join
import waflib.extras.protobuf

proto_files=[
	'abi.proto',
	'tcp_ip.proto',
	'grid.proto',
	'router.proto',
	'region.proto',
	'header.proto']

def build(buildCtx):
    ccNodeList=[]
    protoTaskList=[]
    for proto in proto_files:
	compileTask='protoc_%s' % proto
	protoNode=buildCtx.path.find_node(proto)
	ccNode=protoNode.change_ext('.pb.cc')
	hNode=protoNode.change_ext('.pb.h')
	waflib.extras.protobuf.define_task_gen(buildCtx,
		name=compileTask,
		source=[protoNode],
		target=[ccNode, hNode],
		includes=['.'])
	ccNodeList.append(ccNode)
	protoTaskList.append(compileTask)
	publishTask='cp_%s' % proto
	buildCtx(
		name=publishTask,
		rule='cp ${SRC} ${TGT}',
		source=hNode,
		target=join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), str(hNode)),
		after=[compileTask])
	protoTaskList.append(publishTask)
    buildCtx.shlib(
	    name='shlib_simgrid_grid_db',
	    source=ccNodeList + [
		    buildCtx.path.find_node('about.cxx'),
		    buildCtx.path.find_node('role.cxx'),
		    buildCtx.path.find_node('log_memory.cxx'),
		    buildCtx.path.find_node('log_shm.cxx'),
		    buildCtx.path.find_node('log_mmap.cxx'),
		    buildCtx.path.find_node('mvcc_memory.cxx'),
		    buildCtx.path.find_node('mvcc_shm.cxx'),
		    buildCtx.path.find_node('mvcc_mmap.cxx')],
	    target=join(buildCtx.env.component.build_tree.libPathFromBuild(buildCtx), 'simgrid_grid_db'),
	    includes=buildCtx.env.component.include_path_list,
	    libpath=buildCtx.env.component.lib_path_list,
	    cxxflags=buildCtx.env.CXXFLAGS + ['-DBOOST_CB_DISABLE_DEBUG'],
	    rpath=buildCtx.env.component.rpath_list,
	    install_path=buildCtx.env.component.install_tree.lib,
	    after=protoTaskList)

def install(installCtx):
    return
