from os.path import join

def build(buildCtx):
    for header in [
	    'mmap_container.hpp',
	    'mmap_container.hxx',
	    'exception.hpp',
	    'primitive.hpp',
	    'role.hpp',
	    'handle.hpp']:
	buildCtx(
		rule='cp ${SRC} ${TGT}',
		source=header,
		target=join(buildCtx.env.component.build_tree.includePathFromBuild(buildCtx), header))

def install(buildCtx):
    return
