from os.path import join

def build(buildCtx):
    relativeIncludePath = buildCtx.env.component.build_tree.includeNode(buildCtx).path_from(buildCtx.path.get_bld())
    for header in [
	    'header.hpp']:
	buildCtx(rule='cp ${SRC} ${TGT}', source=header, target=join(relativeIncludePath, header))

def postbuild(buildCtx):
    return

def install(buildCtx):
    return
