import os
from waflib.extras.layout import Product, Component

def name(context):
    return os.path.basename(str(context.path))

def configure(confCtx):
    confCtx.env.component = Component.fromContext(confCtx, name(confCtx), confCtx.env.product)
    confCtx.env.product.addComponent(confCtx.env.component)

def build(buildCtx):
    buildCtx.env.component = buildCtx.env.product.getComponent(name(buildCtx))
    buildCtx.recurse('doc')
    buildCtx.recurse('include')
    buildCtx.recurse('src')
    buildCtx.recurse('test')

def install(installCtx):
    installCtx.env.component = installCtx.env.product.getComponent(name(installCtx))
    installCtx.recurse('doc')
    installCtx.recurse('include')
    installCtx.recurse('src')
